###
# @name get
POST {{url}} HTTP/1.1

{
    "module": "blog",
    "action": "read",
    "parameters": {
        "user": 1
    }
}

###
# @name get
POST {{url}} HTTP/1.1

{
    "module": "blog",
    "action": "read",
    "parameters": {
        "page": 0,
        "max": 1,
        "user": 1
    }
}
