###
# @name login
POST {{url}} HTTP/1.1

{
    "module": "user",
    "action": "login",
    "parameters": {
        "username": "{{username}}",
        "password": "{{password}}"
    }
}

###
@token = {{login.response.body.token}}

###
# @name create
POST {{url}} HTTP/1.1

{
    "module": "blog",
    "action": "update",
    "auth": {
        "token": "{{token}}"
    },
    "parameters": {
        "title": "Post title",
        "summary": "Supreme Space Commander News",
        "body": "{\"array\":[1,2,3],\"boolean\":true,\"null\":null,\"number\":123,\"object\":{\"a\":\"b\",\"c\":\"d\",\"e\":\"f\"},\"string\":\"Hello World\"}",
        "tags": "tag1,tag2,tag3"
    }
}
###
# @name update
POST {{url}} HTTP/1.1

{
    "module": "blog",
    "action": "update",
    "auth": {
        "token": "{{token}}"
    },
    "parameters": {
        "title": "Post title EDITED",
        "summary": "Supreme Space Commander News",
        "body": "{\"array\":[1,2,3],\"boolean\":true,\"null\":null,\"number\":123,\"object\":{\"a\":\"b\",\"c\":\"d\",\"e\":\"f\"},\"string\":\"Hello World\"}",
        "tags": "tag1,tag2,tag3",
        "_id": 1
    }
}

###
# @name get
POST {{url}} HTTP/1.1

{
    "module": "blog",
    "action": "read",
    "auth": {
        "token": "{{token}}"
    },
    "parameters": {
        "user": 1
    }
}
