###
# @name create
POST {{url}} HTTP/1.1

{
    "module": "blog",
    "action": "update",
    "auth": {
        "token": "{{token}}"
    },
    "parameters": {
        "title": "Post title",
        "summary": "Supreme Space Commander News",
        "body": "Full text of the news",
        "tags": "tag1,tag2,tag3"
    }
}
###
# @name update
POST {{url}} HTTP/1.1

{
    "module": "certification",
    "action": "update",
    "auth": {
        "token": "{{token}}"
    },
    "parameters": {
        "title": "Post title EDITED",
        "summary": "Supreme Space Commander News",
        "body": "Full text of the news",
        "tags": "tag1,tag2,tag3",
        "_id": 1
    }
}

###
# @name get
POST {{url}} HTTP/1.1

{
    "module": "certification",
    "action": "read",
    "auth": {
        "token": "{{token}}"
    }
}
