###
# @name login
POST {{url}} HTTP/1.1

{
    "module": "user",
    "action": "login",
    "parameters": {
        "username": "{{username}}",
        "password": "{{password}}"
    }
}

###
@token = {{login.response.body.token}}

###
# @name get
POST {{url}} HTTP/1.1

{
    "module": "certification",
    "action": "read",
    "auth": {
        "token": "{{token}}"
    }
}
