version: "3.9"

networks:
  idealista:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: '${APP_NAME}-server'
    ports:
      - '${APP_PORT}:8080'
    working_dir: /var/www/
    restart: unless-stopped
    volumes:
      - ./app:/var/www/
    depends_on:
      db:
        condition: service_healthy
    command: php -S 0.0.0.0:8080 -t public
    networks:
      - idealista
  db:
    image: mariadb:10.5.9
    container_name: '${APP_NAME}-db'
    restart: always
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - persistent:/var/lib/mysql
      - ./docker/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - idealista
volumes:
 persistent: