###
# @name login
POST {{url}} HTTP/1.1

{
    "module": "user",
    "action": "login",
    "parameters": {
        "username": "{{username}}",
        "password": "{{password}}"
    }
}

###
@token = {{login.response.body.token}}

###
# @name create
POST {{url}} HTTP/1.1

{
    "module": "language",
    "action": "update",
    "auth": {
        "token": "{{token}}"
    },
    "parameters": {
        "name": "Daedri22c",
        "level": "Skyrim"
    }
}
###
# @name update
POST {{url}} HTTP/1.1

{
    "module": "language",
    "action": "update",
    "auth": {
        "token": "{{token}}"
    },
    "parameters": {
        "name": "Daedric+",
        "level": "Skyrim",
        "_id": 1
    }
}

###
# @name get
POST {{url}} HTTP/1.1

{
    "module": "language",
    "action": "read",
    "auth": {
        "token": "{{token}}"
    }
}
