###
# @name login
POST {{url}} HTTP/1.1

{
    "module": "user",
    "action": "login",
    "parameters": {
        "username": "{{username}}",
        "password": "{{password}}"
    }
}

###
@token = {{login.response.body.token}}

###
# @name create
POST {{url}} HTTP/1.1

{
    "module": "position",
    "action": "update",
    "auth": {
        "token": "{{token}}"
    },
    "parameters": {
        "company": "Micro-soft",
        "name": "Web Developer",
        "location": "Vancouver",
        "description": "Bla description bla",
        "startDate": "1999-01-01 00:00:00",
        "endDate": "2019-01-01 00:00:00"
    }
}


###
# @name update
POST {{url}} HTTP/1.1

{
    "module": "position",
    "action": "update",
    "auth": {
        "token": "{{token}}"
    },
    "parameters": {
        "company": "Microsoft",
        "name": "Web Developer",
        "location": "Vancouver",
        "description": "Bla description bla",
        "startDate": "1999-01-01 00:00:00",
        "endDate": "2019-01-01 00:00:00",
        "_id": 1
    }
}

###
# @name get
POST {{url}} HTTP/1.1

{
    "module": "position",
    "action": "read",
    "auth": {
        "token": "{{token}}"
    }
}
