###
# @name login
POST {{url}} HTTP/1.1

{
    "module": "user",
    "action": "login",
    "parameters": {
        "username": "{{username}}",
        "password": "{{password}}"
    }
}

###
@token = {{login.response.body.token}}

###
# @name createPosition
POST {{url}} HTTP/1.1

{
    "module": "education",
    "action": "update",
    "auth": {
        "token": "{{token}}"
    },
    "parameters": {
        "degree": "MIT Software developer",
        "notes": "This is a note",
        "schoolName": "Montreal Institute Techinal",
        "startDate": "2000-01-01 00:00:00",
        "endDate": "2000-01-01 00:00:01"
    }
}
###
# @name update
POST {{url}} HTTP/1.1

{
    "module": "education",
    "action": "update",
    "auth": {
        "token": "{{token}}"
    },
    "parameters": {
        "degree": "MIT Software developer",
        "notes": "This is a note2",
        "schoolName": "Montreal Institute Techinal",
        "startDate": "2000-01-01 00:00:00",
        "endDate": "2000-01-01 00:00:01",
        "_id": 1
    }
}

###
# @name get
POST {{url}} HTTP/1.1

{
    "module": "education",
    "action": "read",
    "auth": {
        "token": "{{token}}"
    }
}
